//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/com.ethnicthv/Game/Input/GamePlay/GamePlayInput.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

namespace com.ethnicthe.Game.Input.GamePlay
{
    public partial class @GamePlayInput: IInputActionCollection2, IDisposable
    {
        public InputActionAsset asset { get; }
        public @GamePlayInput()
        {
            asset = InputActionAsset.FromJson(@"{
    ""name"": ""GamePlayInput"",
    ""maps"": [
        {
            ""name"": ""GamePlay"",
            ""id"": ""bb880e7b-7174-4ef8-961e-652239449d82"",
            ""actions"": [
                {
                    ""name"": ""Touch0Position"",
                    ""type"": ""Value"",
                    ""id"": ""31686684-c61e-4d1e-a5b0-c44a675e5e91"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Touch1Position"",
                    ""type"": ""Value"",
                    ""id"": ""1b214fba-a383-4dc7-813a-8ba77e06e42a"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Touch0Pressed"",
                    ""type"": ""Button"",
                    ""id"": ""981e2785-0149-4f91-828d-90dfe841a4b9"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Touch1Pressed"",
                    ""type"": ""Button"",
                    ""id"": ""d66cb4b7-4a31-4a62-a0d6-075711843f38"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Touch0Delta"",
                    ""type"": ""Value"",
                    ""id"": ""f6887a13-9361-4c1c-bac4-efd93fa6fd37"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Touch0Click"",
                    ""type"": ""Button"",
                    ""id"": ""515e9cf0-2fda-423d-b378-7259605ced2c"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Tap"",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""91abb63a-3d87-4c00-8d19-cf0e0e2eec69"",
                    ""path"": ""<Touchscreen>/primaryTouch/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Touch0Position"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""694130a9-8208-46c8-a411-6b622d8c0792"",
                    ""path"": ""<Touchscreen>/touch1/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Touch1Position"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""42979fd9-24a4-4024-8dc5-b8d9b95f4dc8"",
                    ""path"": ""<Touchscreen>/primaryTouch/press"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Touch0Pressed"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""254b7d2b-739b-4b9f-ae6b-966c16e7021b"",
                    ""path"": ""<Touchscreen>/touch1/press"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Touch1Pressed"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""fba2b013-e85f-4aa2-80a2-63967f2f141f"",
                    ""path"": ""<Pointer>/delta"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Touch0Delta"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7298f08a-bf00-4951-b9a0-93876a5e0f52"",
                    ""path"": ""<Touchscreen>/primaryTouch/tap"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Touch0Click"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
            // GamePlay
            m_GamePlay = asset.FindActionMap("GamePlay", throwIfNotFound: true);
            m_GamePlay_Touch0Position = m_GamePlay.FindAction("Touch0Position", throwIfNotFound: true);
            m_GamePlay_Touch1Position = m_GamePlay.FindAction("Touch1Position", throwIfNotFound: true);
            m_GamePlay_Touch0Pressed = m_GamePlay.FindAction("Touch0Pressed", throwIfNotFound: true);
            m_GamePlay_Touch1Pressed = m_GamePlay.FindAction("Touch1Pressed", throwIfNotFound: true);
            m_GamePlay_Touch0Delta = m_GamePlay.FindAction("Touch0Delta", throwIfNotFound: true);
            m_GamePlay_Touch0Click = m_GamePlay.FindAction("Touch0Click", throwIfNotFound: true);
        }

        public void Dispose()
        {
            UnityEngine.Object.Destroy(asset);
        }

        public InputBinding? bindingMask
        {
            get => asset.bindingMask;
            set => asset.bindingMask = value;
        }

        public ReadOnlyArray<InputDevice>? devices
        {
            get => asset.devices;
            set => asset.devices = value;
        }

        public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

        public bool Contains(InputAction action)
        {
            return asset.Contains(action);
        }

        public IEnumerator<InputAction> GetEnumerator()
        {
            return asset.GetEnumerator();
        }

        IEnumerator IEnumerable.GetEnumerator()
        {
            return GetEnumerator();
        }

        public void Enable()
        {
            asset.Enable();
        }

        public void Disable()
        {
            asset.Disable();
        }

        public IEnumerable<InputBinding> bindings => asset.bindings;

        public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
        {
            return asset.FindAction(actionNameOrId, throwIfNotFound);
        }

        public int FindBinding(InputBinding bindingMask, out InputAction action)
        {
            return asset.FindBinding(bindingMask, out action);
        }

        // GamePlay
        private readonly InputActionMap m_GamePlay;
        private List<IGamePlayActions> m_GamePlayActionsCallbackInterfaces = new List<IGamePlayActions>();
        private readonly InputAction m_GamePlay_Touch0Position;
        private readonly InputAction m_GamePlay_Touch1Position;
        private readonly InputAction m_GamePlay_Touch0Pressed;
        private readonly InputAction m_GamePlay_Touch1Pressed;
        private readonly InputAction m_GamePlay_Touch0Delta;
        private readonly InputAction m_GamePlay_Touch0Click;
        public struct GamePlayActions
        {
            private @GamePlayInput m_Wrapper;
            public GamePlayActions(@GamePlayInput wrapper) { m_Wrapper = wrapper; }
            public InputAction @Touch0Position => m_Wrapper.m_GamePlay_Touch0Position;
            public InputAction @Touch1Position => m_Wrapper.m_GamePlay_Touch1Position;
            public InputAction @Touch0Pressed => m_Wrapper.m_GamePlay_Touch0Pressed;
            public InputAction @Touch1Pressed => m_Wrapper.m_GamePlay_Touch1Pressed;
            public InputAction @Touch0Delta => m_Wrapper.m_GamePlay_Touch0Delta;
            public InputAction @Touch0Click => m_Wrapper.m_GamePlay_Touch0Click;
            public InputActionMap Get() { return m_Wrapper.m_GamePlay; }
            public void Enable() { Get().Enable(); }
            public void Disable() { Get().Disable(); }
            public bool enabled => Get().enabled;
            public static implicit operator InputActionMap(GamePlayActions set) { return set.Get(); }
            public void AddCallbacks(IGamePlayActions instance)
            {
                if (instance == null || m_Wrapper.m_GamePlayActionsCallbackInterfaces.Contains(instance)) return;
                m_Wrapper.m_GamePlayActionsCallbackInterfaces.Add(instance);
                @Touch0Position.started += instance.OnTouch0Position;
                @Touch0Position.performed += instance.OnTouch0Position;
                @Touch0Position.canceled += instance.OnTouch0Position;
                @Touch1Position.started += instance.OnTouch1Position;
                @Touch1Position.performed += instance.OnTouch1Position;
                @Touch1Position.canceled += instance.OnTouch1Position;
                @Touch0Pressed.started += instance.OnTouch0Pressed;
                @Touch0Pressed.performed += instance.OnTouch0Pressed;
                @Touch0Pressed.canceled += instance.OnTouch0Pressed;
                @Touch1Pressed.started += instance.OnTouch1Pressed;
                @Touch1Pressed.performed += instance.OnTouch1Pressed;
                @Touch1Pressed.canceled += instance.OnTouch1Pressed;
                @Touch0Delta.started += instance.OnTouch0Delta;
                @Touch0Delta.performed += instance.OnTouch0Delta;
                @Touch0Delta.canceled += instance.OnTouch0Delta;
                @Touch0Click.started += instance.OnTouch0Click;
                @Touch0Click.performed += instance.OnTouch0Click;
                @Touch0Click.canceled += instance.OnTouch0Click;
            }

            private void UnregisterCallbacks(IGamePlayActions instance)
            {
                @Touch0Position.started -= instance.OnTouch0Position;
                @Touch0Position.performed -= instance.OnTouch0Position;
                @Touch0Position.canceled -= instance.OnTouch0Position;
                @Touch1Position.started -= instance.OnTouch1Position;
                @Touch1Position.performed -= instance.OnTouch1Position;
                @Touch1Position.canceled -= instance.OnTouch1Position;
                @Touch0Pressed.started -= instance.OnTouch0Pressed;
                @Touch0Pressed.performed -= instance.OnTouch0Pressed;
                @Touch0Pressed.canceled -= instance.OnTouch0Pressed;
                @Touch1Pressed.started -= instance.OnTouch1Pressed;
                @Touch1Pressed.performed -= instance.OnTouch1Pressed;
                @Touch1Pressed.canceled -= instance.OnTouch1Pressed;
                @Touch0Delta.started -= instance.OnTouch0Delta;
                @Touch0Delta.performed -= instance.OnTouch0Delta;
                @Touch0Delta.canceled -= instance.OnTouch0Delta;
                @Touch0Click.started -= instance.OnTouch0Click;
                @Touch0Click.performed -= instance.OnTouch0Click;
                @Touch0Click.canceled -= instance.OnTouch0Click;
            }

            public void RemoveCallbacks(IGamePlayActions instance)
            {
                if (m_Wrapper.m_GamePlayActionsCallbackInterfaces.Remove(instance))
                    UnregisterCallbacks(instance);
            }

            public void SetCallbacks(IGamePlayActions instance)
            {
                foreach (var item in m_Wrapper.m_GamePlayActionsCallbackInterfaces)
                    UnregisterCallbacks(item);
                m_Wrapper.m_GamePlayActionsCallbackInterfaces.Clear();
                AddCallbacks(instance);
            }
        }
        public GamePlayActions @GamePlay => new GamePlayActions(this);
        public interface IGamePlayActions
        {
            void OnTouch0Position(InputAction.CallbackContext context);
            void OnTouch1Position(InputAction.CallbackContext context);
            void OnTouch0Pressed(InputAction.CallbackContext context);
            void OnTouch1Pressed(InputAction.CallbackContext context);
            void OnTouch0Delta(InputAction.CallbackContext context);
            void OnTouch0Click(InputAction.CallbackContext context);
        }
    }
}
